name: CD Pipeline

on:
  push:
    branches:
      - bayanna         # Use your working branch
  workflow_dispatch:     # Optional manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "✅ AWS credentials configured."

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: List Terraform files
        run: ls -R
        working-directory: Terraform

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: Terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Terraform

